<cfset thisDir = getDirectoryFromPath(getCurrentTemplatePath())>
<cfset files = directoryList(thisDir, false, "array", "*Test.cfc")>
<cfdump var="#files#">

<cfloop array="#files#" index="f">
	<cfset testName = listFirst( getFileFromPath(f), "." )>
	<cfoutput>#testName#</cfoutput>
	<cfset output = "
		<!--- NOTE: This test generated by #getFileFromPath(getCurrentTemplatePath())# --->
		<cfcomponent extends='cfmongodb.test.#testName#'>
			<cfset factoryType = 'cfmongodb.core.DefaultFactory'>
		</cfcomponent>
	">

	<cfoutput>

	#output# <br>

	</cfoutput>

	<cfset withCFJavaLoaderDir = thisDir & "/withCFJavaLoader/">
	<cfset withLibsFromCFClasspathDir = thisDir & "/withLibsFromCFClasspath/">

	<cffile action="write" file="#withCFJavaLoaderDir#/#testName#.cfc" output="#output#">
	<cffile action="write" file="#withLibsFromCFClasspathDir#/#testName#.cfc" output="#output#">


</cfloop>