
		<!--- NOTE: This test generated by GenerateSubclassTests.cfm --->
		<cfcomponent extends='cfmongodb.test.AggregationTest'>
			<cfset factoryType = 'cfmongodb.core.DefaultFactory'>
		</cfcomponent>
	
